# name of your github action
name: Build Prod
# this will help you specify where to run 
on:
  workflow_dispatch:
  push:
    branches:
    # this will run on the electron branch
      - master
# this is where the magic happens, each job happens in parallel btw

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci && npm install -g electron-builder
    - name: If building Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest'}}
      run: sudo snap install snapcraft --classic
    - name: Build App
      env: 
        CI: false
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: ls && npm run electron:pro-build --if-present
    - name: Upload artifacts Windows
      if: ${{ matrix.os == 'windows-latest'}}
      uses: actions/upload-artifact@v2
      with:
        name: windows-artifacts
        path: dist/*.exe
    - name: Upload artifacts Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest'}}
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-artifacts
        path: |
          dist/*.AppImage
          dist/*.snap
    - name: Upload artifacts MacOs
      if: ${{ matrix.os == 'macos-latest'}}
      uses: actions/upload-artifact@v2
      with:
        name: macos-artifacts
        path: |
          dist/*.dmg
          dist/*.zip
