name: Publish Prod

on:
  workflow_dispatch:
  

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
    - run: npm ci && npm install -g electron-builder
    - name: If building Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest'}}
      run: sudo snap install snapcraft --classic
    - name: Build App
      env: 
        CI: false
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run electron:publish --if-present
    
